---
- name: Dummy tasks
  hosts: all[0]
  gather_facts: no
  tasks:
    - debug: msg="Dummy tags"
      tags: ["unsafe", "skip-vagrant", "wip"]

- name: Gather all facts
  hosts: all
  tasks: []

- name: Intialize Vagrant Hosts
  hosts: all
  roles:
    - {role: vagrant, when: "ansible_env['SUDO_USER'] | default('') == 'vagrant'"}

#- name: Install Globus CLI
#  become: yes
#  become_method: sudo
#  hosts: globus-servers
#  tasks:
#  - name: pip install globus-cli
#    command: pip install globus-cli
#  roles:
#    - {role: gridftp, gridftp_mode: server}

#- name: gridftp clients
#  hosts: gridftp-clients
#  roles:
#    - {role: gridftp, gridftp_mode: client}

#- name: simpleca servers
#  hosts: localhost #gridftp-servers
#  roles:
#    - {role: simpleca, simpleca_mode: server}

#- name: simpleca clients
#  hosts: gridftp-clients
#  roles:
#    - {role: simpleca, simpleca_mode: client}
